##### Copyright 2019 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 初学者的 TensorFlow 2.0 教程

<table class="tfo-notebook-buttons" align="left">
  <td>     <a target="_blank" href="https://tensorflow.google.cn/tutorials/quickstart/beginner"><img src="https://tensorflow.google.cn/images/tf_logo_32px.png">在 TensorFlow.org 观看</a>   </td>
  <td><a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/quickstart/beginner.ipynb"><img src="https://tensorflow.google.cn/images/colab_logo_32px.png">在 Google Colab 中运行 </a></td>
  <td>     <a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/quickstart/beginner.ipynb"><img src="https://tensorflow.google.cn/images/GitHub-Mark-32px.png">在 GitHub 查看源代码</a>   </td>
  <td>     <a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/zh-cn/tutorials/quickstart/beginner.ipynb"><img src="https://tensorflow.google.cn/images/download_logo_32px.png">下载笔记本</a>   </td>
</table>

此简短介绍使用 [Keras](https://tensorflow.google.cn/guide/keras/overview) 进行以下操作：

1. 加载一个预构建的数据集。
2. 构建对图像进行分类的神经网络机器学习模型。
3. 训练此神经网络。
4. 评估模型的准确率。

这是一个 [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) 笔记本文件。 Python程序可以直接在浏览器中运行，这是学习 Tensorflow 的绝佳方式。想要学习该教程，请点击此页面顶部的按钮，在Google Colab中运行笔记本。

1. 在 Colab中, 连接到Python运行环境： 在菜单条的右上方, 选择 *CONNECT*。
2. 运行所有的代码块: 选择 *Runtime* &gt; *Run all*。

## 设置 TensorFlow

首先将 TensorFlow 导入到您的程序：

In [2]:
import tensorflow as tf

如果您在自己的开发环境而不是 [Colab](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb) 中操作，请参阅设置 TensorFlow 以进行开发的[安装指南](https://tensorflow.google.cn/install)。

注：如果您使用自己的开发环境，请确保您已升级到最新的 `pip` 以安装 TensorFlow 2 软件包。有关详情，请参阅[安装指南](https://tensorflow.google.cn/install)。

## 加载数据集

加载并准备 [MNIST 数据集](http://yann.lecun.com/exdb/mnist/)。将样本数据从整数转换为浮点数：

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train)
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0

## 构建机器学习模型

通过堆叠层来构建 `tf.keras.Sequential` 模型。

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)), #Flatten层用于将输入数据从二维数组（例如图像）展平为一维数组
  tf.keras.layers.Dense(128, activation='relu'), #Dense层，也称为全连接层
  tf.keras.layers.Dropout(0.2), #Dropout随机地丢弃一部分神经元的输出，这有助于增强模型的泛化能力，每个神经元的输出都有20%的概率被设置为零
  tf.keras.layers.Dense(10) #添加了一个输出层。这是一个Dense层，由10个神经元组成
])
#第一层：Flatten层，没有神经元，仅用于数据展平。它将输入数据从28x28的二维数组转换为大小为784的一维数组，用于输入到后续的神经网络层中。
#第二层：Dense层，有128个神经元，使用ReLU激活函数。这一层的输入是大小为784的一维向量，每个神经元都与输入的每个元素相连，共有784x128个连接权重。
#第三层：Dropout层，没有神经元，用于正则化。Dropout层没有神经元输出，而是随机地以一定概率丢弃前一层的神经元输出。在这里，丢弃的概率为20%，用于减少过拟合的可能性。
#第四层：Dense层，有10个神经元，用于输出分类得分。这一层的输入是来自前一层的128维输出，每个神经元都与128个输入连接，共有128x10个连接权重。该层没有指定激活函数，因此输出是原始的得分值，用于后续通过Softmax函数计算各个类别的概率分布。

对于每个样本，模型都会返回一个包含 [logits](https://developers.google.com/machine-learning/glossary#logits) 或 [log-odds](https://developers.google.com/machine-learning/glossary#log-odds) 分数的向量，每个类一个。

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.31723687,  0.04468291, -0.09986597,  0.35093924,  0.08325072,
         0.44599754,  0.290999  , -0.2337882 ,  0.45255098, -0.18407862]],
      dtype=float32)

`tf.nn.softmax` 函数将这些 logits 转换为每个类的*概率*：

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.11514709, 0.08767672, 0.07587654, 0.11909395, 0.09112427,
        0.13097036, 0.11216517, 0.06636602, 0.13183148, 0.06974843]],
      dtype=float32)

注：可以将 `tf.nn.softmax` 烘焙到网络最后一层的激活函数中。虽然这可以使模型输出更易解释，但不建议使用这种方式，因为在使用 softmax 输出时不可能为所有模型提供精确且数值稳定的损失计算。

使用 `losses.SparseCategoricalCrossentropy` 为训练定义损失函数，它会接受 logits 向量和 `True` 索引，并为每个样本返回一个标量损失。

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
#tf.keras.losses.SparseCategoricalCrossentropy 是 TensorFlow 中的一个损失函数，用于多类别分类问题（单标签分类问题）的训练。
#在这个损失函数中，from_logits=True表示该函数将处理原始的 logits（得分值），而不需要在输出层使用 softmax 函数。这意味着在模型的最后一层不需要显式地添加 softmax 激活函数，
#适用于单标签分类问题时，标签是整数形式的类别标签，而不是经过 one-hot 编码的向量。例如，对于10个类别的分类问题，标签可以是从0到9的整数。这是与CategoricalCrossentropy不同之处，后者适用于one-hot编码的标签。


此损失等于 true 类的负对数概率：如果模型确定类正确，则损失为零。

这个未经训练的模型给出的概率接近随机（每个类为 1/10），因此初始损失应该接近 `-tf.math.log(1/10) ~= 2.3`。

In [15]:
loss_fn(y_train[:1], predictions).numpy()
#至于计算，是先把y_train[:1]变成one-hot,predictions变成概率分布，然后用交叉熵

2.0327842

在开始训练之前，使用 Keras `Model.compile` 配置和编译模型。将 [`optimizer`](https://tensorflow.google.cn/api_docs/python/tf/keras/optimizers) 类设置为 `adam`，将 `loss` 设置为您之前定义的 `loss_fn` 函数，并通过将 `metrics` 参数设置为 `accuracy` 来指定要为模型评估的指标。

In [16]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
#Adam具有动量梯度下降，RMSProp（Root Mean Square Propagation）算法（使得较小梯度的方向可以拥有更大的学习率，而较大梯度的方向可以拥有较小的学习率），自适应学习率调整。
#m = β1 * m + (1 - β1) * g
#v = β2 * v + (1 - β2) * g^2
#其中g是梯度，β1 和 β2 是动量和梯度平方的指数衰减率，一般取较接近于1的数值，如 0.9 和 0.999
#m_hat = m / (1 - β1^t)   # t 表示当前迭代次数
#v_hat = v / (1 - β2^t)
#θ = θ - α * m_hat / (√v_hat + ε)


## 训练并评估模型

使用 `Model.fit` 方法调整您的模型参数并最小化损失：

In [17]:
model.fit(x_train, y_train, epochs=5)
#其它参数：
#batch_size（可选）：用于指定每个训练批次（batch）的样本数量。如果没有指定，将使用默认值。
#validation_data（可选）：用于提供验证数据集，可以在训练过程中监控模型在验证集上的性能。
#其他优化参数（例如学习率、动量等）和回调函数等（在这里未给出）。

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3011 - accuracy: 0.9116
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1482 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1126 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0896 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0777 - accuracy: 0.9757


`Model.evaluate` 方法通常在 "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" 或 "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)" 上检查模型性能。

In [30]:
model.evaluate(x_test,  y_test, verbose=2,batch_size = 32)
print(x_test.shape)
#第一个输出是batch个数

313/313 - 0s - loss: 0.0760 - accuracy: 0.9754 - 340ms/epoch - 1ms/step
(10000, 28, 28)


现在，这个照片分类器的准确度已经达到 98%。想要了解更多，请阅读 [TensorFlow 教程](https://tensorflow.google.cn/tutorials/)。

如果您想让模型返回概率，可以封装经过训练的模型，并将 softmax 附加到该模型：

In [31]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [36]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.3044210e-07, 2.7680482e-08, 2.1950749e-05, 9.1927017e-05,
        2.8365631e-11, 1.2679867e-08, 1.9586541e-13, 9.9988174e-01,
        1.9482201e-07, 3.7463085e-06],
       [7.3102854e-07, 3.4969937e-06, 9.9998415e-01, 1.1524755e-05,
        1.4347884e-17, 1.4223980e-07, 3.4725423e-09, 5.7348569e-14,
        8.3399252e-09, 1.0740519e-13],
       [4.7125042e-07, 9.9856925e-01, 2.4213105e-05, 4.1816187e-05,
        2.0040230e-04, 6.9923926e-06, 1.5271435e-05, 5.8625673e-04,
        5.5414543e-04, 1.2235249e-06],
       [9.9993336e-01, 3.0579181e-07, 7.3624738e-06, 1.2443793e-07,
        1.8494285e-06, 6.0086518e-06, 1.0664439e-05, 2.6996022e-05,
        9.4106465e-09, 1.3374417e-05],
       [3.8704110e-07, 1.6672757e-09, 1.1380639e-05, 4.7194760e-08,
        9.8252052e-01, 2.3614730e-06, 2.7504333e-07, 3.9820188e-05,
        1.0255123e-06, 1.7424155e-02]], dtype=float32)>

## 结论

恭喜！您已经利用 [Keras](https://tensorflow.google.cn/guide/keras/overview) API 借助预构建数据集训练了一个机器学习模型。

有关使用 Keras 的更多示例，请查阅[教程](https://tensorflow.google.cn/tutorials/keras/)。要详细了解如何使用 Keras 构建模型，请阅读[指南](https://tensorflow.google.cn/guide/keras)。如果您想详细了解如何加载和准备数据，请参阅有关[图像数据加载](https://tensorflow.google.cn/tutorials/load_data/images)或 [CSV 数据加载](https://tensorflow.google.cn/tutorials/load_data/csv)的教程。
